---
all:
  children:
    ot_hosts:
      hosts:
        rhel01.nostromo.io:
        rhel03.nostromo.io:
    report_host:
      hosts:
        rhel02.nostromo.io:
          ansible_host: 192.168.88.103
  vars:
    ansible_user: root
