---
- name: Restart falco
  ansible.builtin.systemd:
    name: "falco-{{ falco_driver | default('modern_ebpf') }}"
    state: restarted
    enabled: true

- name: Restart falcosidekick
  ansible.builtin.systemd:
    name: falcosidekick
    state: restarted
    enabled: true
