---
- name: Restart fapolicyd
  ansible.builtin.systemd:
    name: fapolicyd
    state: restarted
    daemon_reload: true

- name: Update fapolicyd trust database
  ansible.builtin.command:
    cmd: fapolicyd-cli --update
  changed_when: true
